### ISSUE TITLE
remove boilerplates using justText or other 3rd library

### ISSUE THREAD

**Issue by don-han** [BIDS-projects/lda#21]
Refer #18

**Comment by chewisinho** [comment]
Boilerplates mostly removed, but still remnants such as "spambots", "email address", "dot edu", "javascript enabled view"

**Comment by don-han** [comment]
Hm, do they appear after topic modeling?

**Comment by chewisinho** [comment]
They appear after using justext and are fed into topic-modeling. We need to filter them out (I think justext got rid of most of them, like "skip main content")

**Comment by don-han** [comment]
Implemented at BIDS-projects/ETL
